#!/usr/bin/env python3
# /// script
# requires-python = ">=3.10"
# dependencies = ["google-genai>=1.0.0", "requests>=2.28.0", "pillow>=10.0.0"]
# ///
"""
EXP-V7-028 Runner: Text-Only vs AI Reference Image Consistency Test (Realistic)

Conditions:
  A: Text-only (no reference images)
  B: With AI-generated illustration-style reference images

Both conditions use identical storyboard prompts. Condition B adds
reference images generated by Gemini in "digital painting" style
(to bypass Seedance privacy filter).
"""

import json
import os
import subprocess
import sys
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from pathlib import Path

PROJ = Path.home() / "trinity-v7-consistency"
EXP = PROJ / "experiments" / "exp-v7-028"
ASSETS = EXP / "assets"
OUTPUT = EXP / "output"
TOOLS = PROJ / "tools"

os.makedirs(ASSETS, exist_ok=True)
os.makedirs(OUTPUT, exist_ok=True)
os.chdir(PROJ)

sys.path.insert(0, str(TOOLS))
from config_loader import load_keys

KEYS = load_keys()

# ── Character / Scene Descriptions ──────────────────────────────────
MAN_DESC = (
    "Digital painting portrait of a 30-year-old Chinese man with short neat black hair "
    "parted to the side, slim angular face, wearing a solid black turtleneck sweater. "
    "3D rendered illustration style, soft studio lighting, clean background. "
    "NOT a photograph. Anime-inspired semi-realistic digital art."
)
WOMAN_DESC = (
    "Digital painting portrait of a 28-year-old Chinese woman with long wavy brown hair "
    "past her shoulders, soft oval face, wearing a beige trench coat over a white collared blouse. "
    "3D rendered illustration style, soft studio lighting, clean background. "
    "NOT a photograph. Anime-inspired semi-realistic digital art."
)
CAFE_DESC = (
    "Digital painting of a cozy coffee shop interior. Small round wooden table with two white "
    "ceramic latte cups. Warm afternoon sunlight through a window with sheer curtains. "
    "Wooden furniture, warm tones. Illustrated environment concept art style."
)

# ── Seedance Prompts (shared between conditions) ───────────────────
CHAR_TEXT = (
    "A 30-year-old Chinese East Asian man with short black hair parted to the side, slim angular face, "
    "wearing a solid black turtleneck sweater. A 28-year-old Chinese East Asian woman with long wavy "
    "brown hair, soft oval face, wearing a beige trench coat over a white blouse."
)

SEG1_PROMPT = (
    f"A cozy cafe, afternoon sunlight through sheer curtains, small wooden table with two lattes. "
    f"{CHAR_TEXT} "
    f"The man sits on the right, picks up his coffee cup and tilts it to his lips, looking at the woman over the rim. "
    f"The woman holds her cup with both hands, looking down at the latte art, smiling gently. "
    f"She looks up, puts down the cup, tucks a strand of curly hair behind her ear, eyes brightening. "
    f"The man puts down his cup, leans forward attentively. "
    f"The man raises his eyebrows and grins widely, tapping the table once with his right hand. "
    f"The woman crosses her hands on the table, smiling proudly, chin slightly raised. "
    f"The woman raises her cup in a toast gesture. The man raises his cup too. They gently clink cups above the table, "
    f"smiling at each other warmly. "
    f"Normal speed movement, natural pacing. No slow motion. No facing camera directly. No subtitles. "
    f"Vertical 9:16 framing. Medium shot, slightly angled right 10 degrees. Both characters in frame."
)

SEG2_PROMPT = (
    f"Continuing in the same cozy cafe. {CHAR_TEXT} "
    f"They just clinked cups. The woman puts down her cup, expression turning serious, leaning back slightly, "
    f"looking out the window. The man notices, holding his cup mid-sip, looking at her with concern. "
    f"Afternoon sunlight on the woman's profile. "
    f"The man slowly puts down his cup, crosses hands on table, leans forward, watching her intently. "
    f"The woman turns back to face him, tired but determined look in her eyes. "
    f"The woman takes a deep breath, a smile gradually forming, right fist gently clenched on table. "
    f"The man smiles too, gently patting her fist on the table with his left hand. "
    f"They smile at each other. The woman picks up coffee and sips slowly. The man leans back relaxed, watching her. "
    f"Warm peaceful atmosphere, sunlight even warmer. "
    f"Normal speed movement, natural pacing. No slow motion. No facing camera directly. No subtitles. "
    f"Same camera angle as previous segment. Medium shot, slightly angled right 10 degrees."
)


def gen_ref_images():
    """Generate illustration-style reference images via Gemini."""
    specs = [
        {"name": "man-illustration", "type": "character", "style": "realistic", "desc": MAN_DESC},
        {"name": "woman-illustration", "type": "character", "style": "realistic", "desc": WOMAN_DESC},
        {"name": "cafe-illustration", "type": "scene", "style": "realistic", "desc": CAFE_DESC},
    ]
    specs_path = EXP / "asset-specs-v2.json"
    with open(specs_path, "w") as f:
        json.dump(specs, f, indent=2, ensure_ascii=False)

    cmd = [
        "python3", "-u", str(TOOLS / "gemini_chargen.py"),
        "--specs", str(specs_path),
        "--out-dir", str(ASSETS),
    ]
    print("=== Step 1: Generating illustration-style reference images ===", flush=True)
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
    print(r.stdout, flush=True)
    if r.stderr:
        print(r.stderr, file=sys.stderr, flush=True)

    # Check outputs
    expected = [ASSETS / "char-man-illustration.webp", ASSETS / "char-woman-illustration.webp", ASSETS / "scene-cafe-illustration.webp"]
    for p in expected:
        if p.exists():
            print(f"  ✓ {p.name} ({p.stat().st_size // 1024}KB)", flush=True)
        else:
            print(f"  ✗ MISSING {p.name}", flush=True)
    return [str(p) for p in expected if p.exists()]


def run_seedance(prompt, images=None, video=None, output="output.mp4"):
    """Run seedance_gen.py for one video."""
    cmd = [
        "python3", "-u", str(TOOLS / "seedance_gen.py"),
        "--prompt", prompt,
        "--ratio", "9:16",
        "--duration", "15",
        "--out", output,
    ]
    if video:
        cmd.extend(["--video", video])
    for img in (images or []):
        cmd.extend(["--image", img])

    print(f"  Seedance → {os.path.basename(output)}", flush=True)
    t0 = time.time()
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=1800,
                       env={**os.environ, "PYTHONUNBUFFERED": "1"})
    elapsed = time.time() - t0
    print(r.stdout, flush=True)
    ok = r.returncode == 0 and os.path.isfile(output)
    err = r.stderr if not ok else ""
    if err:
        print(f"  ✗ Error: {err[:500]}", file=sys.stderr, flush=True)
    return {"ok": ok, "path": output, "elapsed": elapsed, "error": err[:1000]}


def check_audio(path):
    """Check if video has audio track via ffprobe."""
    try:
        r = subprocess.run(
            ["ffprobe", "-v", "error", "-select_streams", "a", "-show_entries",
             "stream=codec_type", "-of", "csv=p=0", path],
            capture_output=True, text=True, timeout=30
        )
        has_audio = "audio" in r.stdout
        print(f"  Audio check {os.path.basename(path)}: {'✓' if has_audio else '✗ NO AUDIO'}", flush=True)
        return has_audio
    except Exception as e:
        print(f"  Audio check error: {e}", flush=True)
        return False


def concat_segments(seg1, seg2, output):
    """Concatenate two segments."""
    cmd = [
        "python3", "-u", str(TOOLS / "ffmpeg_concat.py"),
        "--inputs", seg1, seg2,
        "--output", output,
    ]
    r = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
    print(r.stdout, flush=True)
    return os.path.isfile(output)


def main():
    gen_log = {"experiment": "EXP-V7-028", "timestamp": time.strftime("%Y-%m-%dT%H:%M:%S%z"), "conditions": {}}

    # Step 1: Generate reference images
    ref_images = gen_ref_images()

    # Step 2 & 3: Run Seg1 for both conditions concurrently
    print("\n=== Step 2-3: Generating Seg1 (concurrent A+B) ===", flush=True)
    seg1_results = {}
    condA_seg1 = str(OUTPUT / "condA-seg1.mp4")
    condB_seg1 = str(OUTPUT / "condB-seg1.mp4")

    with ThreadPoolExecutor(max_workers=2) as ex:
        futures = {
            ex.submit(run_seedance, SEG1_PROMPT, None, None, condA_seg1): "condA",
            ex.submit(run_seedance, SEG1_PROMPT, ref_images if ref_images else None, None, condB_seg1): "condB",
        }
        for fut in as_completed(futures):
            cond = futures[fut]
            seg1_results[cond] = fut.result()
            gen_log["conditions"][f"{cond}-seg1"] = {
                "prompt": SEG1_PROMPT[:200] + "...",
                "images": ref_images if cond == "condB" else [],
                "result": seg1_results[cond],
            }

    # Step 4: Run Seg2 via video extension (concurrent, only if Seg1 succeeded)
    print("\n=== Step 4: Generating Seg2 via video extension (concurrent) ===", flush=True)
    seg2_results = {}
    condA_seg2 = str(OUTPUT / "condA-seg2.mp4")
    condB_seg2 = str(OUTPUT / "condB-seg2.mp4")

    seg2_tasks = {}
    with ThreadPoolExecutor(max_workers=2) as ex:
        if seg1_results.get("condA", {}).get("ok"):
            seg2_tasks[ex.submit(run_seedance, SEG2_PROMPT, None, condA_seg1, condA_seg2)] = "condA"
        else:
            print("  ✗ Skipping condA Seg2 (Seg1 failed)", flush=True)

        if seg1_results.get("condB", {}).get("ok"):
            seg2_tasks[ex.submit(run_seedance, SEG2_PROMPT, ref_images if ref_images else None, condB_seg1, condB_seg2)] = "condB"
        else:
            print("  ✗ Skipping condB Seg2 (Seg1 failed)", flush=True)

        for fut in as_completed(seg2_tasks):
            cond = seg2_tasks[fut]
            seg2_results[cond] = fut.result()
            gen_log["conditions"][f"{cond}-seg2"] = {
                "prompt": SEG2_PROMPT[:200] + "...",
                "result": seg2_results[cond],
            }

    # Step 5: Concatenate
    print("\n=== Step 5: Concatenation ===", flush=True)
    finals = {}
    for cond in ["condA", "condB"]:
        s1 = str(OUTPUT / f"{cond}-seg1.mp4")
        s2 = str(OUTPUT / f"{cond}-seg2.mp4")
        final = str(OUTPUT / f"{cond}-final.mp4")
        if os.path.isfile(s1) and os.path.isfile(s2):
            ok = concat_segments(s1, s2, final)
            finals[cond] = final if ok else None
            print(f"  {cond} concat: {'✓' if ok else '✗'}", flush=True)
        else:
            print(f"  {cond} concat: SKIP (missing segments)", flush=True)

    # Step 6: Audio check
    print("\n=== Step 6: Audio Check ===", flush=True)
    for f in sorted(OUTPUT.glob("*.mp4")):
        check_audio(str(f))

    # Save generation log
    gen_log["finals"] = finals
    log_path = OUTPUT / "generation-log.json"
    with open(log_path, "w") as f:
        json.dump(gen_log, f, indent=2, ensure_ascii=False)
    print(f"\n✓ Generation log saved: {log_path}", flush=True)

    # Summary
    print("\n=== Summary ===", flush=True)
    for cond in ["condA", "condB"]:
        s1_ok = seg1_results.get(cond, {}).get("ok", False)
        s2_ok = seg2_results.get(cond, {}).get("ok", False)
        final_ok = cond in finals and finals[cond]
        print(f"  {cond}: Seg1={'✓' if s1_ok else '✗'} Seg2={'✓' if s2_ok else '✗'} Final={'✓' if final_ok else '✗'}", flush=True)

    # Check for privacy filter specifically
    for cond in ["condA", "condB"]:
        for seg in ["seg1", "seg2"]:
            key = f"{cond}-{seg}"
            result = gen_log["conditions"].get(key, {}).get("result", {})
            if "PrivacyInformation" in result.get("error", ""):
                print(f"\n⚠️  PRIVACY FILTER BLOCK on {key}! Reference images detected as real person.", flush=True)
                print("  → Need to try more stylized/anime approach or report to Controller.", flush=True)


if __name__ == "__main__":
    main()
